name = "creative-studio"
compatibility_date = "2025-11-20"

d1_databases = [
  { binding = "DB", database_name = "suno-db", database_id = "94b69358-2fa3-4c54-87c0-5e716ea08444" }
]

[[r2_buckets]]
binding = "MUSIC_BUCKET"  
bucket_name = "creative-studio-music"       

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true

