name = "creative-studio"
compatibility_date = "2025-11-20"

d1_databases = [
  { binding = "DB", database_name = "suno-db", database_id = "61098853-a4b4-4cde-9c04-4cf4d0984ae7" }
]

[[r2_buckets]]
binding = "MUSIC_BUCKET"  
bucket_name = "creative-studio-music"       

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true